name: Install Nginx on EC2

on:
  push:
    branches:
      - main  # Triggers deployment on push to the main branch
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Deploy Nginx on EC2
        env:
          HOST: ${{ secrets.EC2_PUBLIC_IP }}
          USER: ubuntu  # Change to 'ec2-user' for Amazon Linux
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST << 'EOF'
          sudo apt update -y
          sudo apt install nginx -y
          sudo systemctl start nginx
          sudo systemctl enable nginx
          echo "<h1>Welcome to Nginx Server</h1>" | sudo tee /var/www/html/index.html
          EOF
